Repository TwilioQuest/twilioquest-dev-fundamentals, pull requests merged in 2022-11, with the labels that each got.

#37 Add fs-07-rm objective
  levels/tower_of_knowledge/level.json
  levels/tower_of_knowledge/objectives/fs-07-rm/description.md
  levels/tower_of_knowledge/objectives/fs-07-rm/objective.json
  levels/tower_of_knowledge/objectives/fs-07-rm/validator.js
  levels/tower_of_knowledge/objectives/fs-07-rm/walkthrough.md
Labels: feature

#38 Add fs-08-hidden
  levels/tower_of_knowledge/level.json
  levels/tower_of_knowledge/objectives/fs-08-hidden/description.md
  levels/tower_of_knowledge/objectives/fs-08-hidden/objective.json
  levels/tower_of_knowledge/objectives/fs-08-hidden/validator.js
  levels/tower_of_knowledge/objectives/fs-08-hidden/walkthrough.md
Labels: feature

#46 Added isDirectory Check
  levels/tower_of_knowledge/objectives/fs-05-mkdir/validator.js
Labels: bug

#41 File System Initial Map Extension Mockup
  levels/tower_of_knowledge/events.js
  levels/tower_of_knowledge/maps/file-system.json
Labels: proposal
